oop-four-pillars/force-app/main/default/objects/Course_Attendee__c/Course_Attendee__c.object-meta.xml
<CustomObject>
    <description>Used to track a student who attends a course.</description>
    <label>Course Attendee</label>
    <nameField>
        <displayFormat>ATTENDEE-{00000}</displayFormat>
        <label>Course Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course_Attendee__c/fields/Course_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Course_Delivery__c</fullName>
    <description>Course delivery that student is attending.</description>
    <label>Course Delivery</label>
    <referenceTo>Course_Delivery__c</referenceTo>
    <relationshipLabel>Course Attendees</relationshipLabel>
    <relationshipName>Course_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Attendee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of course attendee.</description>
    <inlineHelpText>Enrolled - Student is enrolled in course delivery.
Completed - Student attended course delivery.
Course Cancelled - AW Computing cancelled course delivery.
No Show - Student did not show up for course delivery.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Course Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Attendee__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Contact who is attending the course delivery.</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Technician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Attendees</relationshipLabel>
    <relationshipName>Course_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/Course_Delivery__c.object-meta.xml
<CustomObject>
    <description>Used to track each time a course is delivered.</description>
    <label>Course Delivery</label>
    <nameField>
        <displayFormat>DELIVERY-{00000}</displayFormat>
        <label>Course Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the course delivery.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DEX450_Exercises/force-app/main/default/classes/CourseAttendeeTriggerHandler.cls
public class CourseAttendeeTriggerHandler {
    
    public static void provideAccessLMS (List<Course_Attendee__c> courseAttendees, Map<Id,Course_Attendee__c> oldMap) {
        List<Id> courseAttendeesToChangeAccess = new List <Id>();
        for (Course_Attendee__c cA : courseAttendees) {
            if (cA.status__c == 'Enrolled') {
                if (oldMap == null || !oldMap.containsKey(cA.Id) || oldMap.get(cA.id).status__c != cA.status__c) {
                    courseAttendeesToChangeAccess.add(cA.Id);
                }  
            }
        }
        notifyForLMSAccess(courseAttendeesToChangeAccess);
    }
   
    private static void notifyForLMSAccess(List<Id> idsToChangeAccess) {
        if (idsToChangeAccess.size() > 0) {
            String emails = '';
            Integer numberOfNewEnrollees = 0;
            for (List<Course_Attendee__c> caList : [SELECT Course_Delivery__r.Name, Student__r.email 
                                                          FROM Course_Attendee__c 
                                                          WHERE Id in :idsToChangeAccess
                                                          ORDER BY Course_Delivery__r.Name]) {
                for (Course_Attendee__c ca: caList) {
                    emails += '\n' + ca.Course_Delivery__r.Name + ': ' + ca.Student__r.email; 
                    numberOfNewEnrollees++;
                }             
            }
            List<User> TrainingCoordinatorIds = [SELECT Id FROM User WHERE ProfileId IN 
                                                 (Select Id from Profile where name = 'Training User')];
            Task newTask = new Task(Subject='Add ' + numberOfNewEnrollees + ' new Enrollees to LMS',
                                    Description = 'Provide access for: ' + emails,
                                    Priority = 'Normal', 
                                    OwnerId = TrainingCoordinatorIds[0].Id);             
            insert newTask;
        }
    }
}