oop-four-pillars/force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Candidate__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <formula>LOWER(Last_Name__c &amp; Email__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unique Key</label>
    <type>Text</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Job_Application__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Candidate__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Job_Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Phone Screen</fullName>
            </value>
            <value>
                <fullName>Schedule Interviews</fullName>
            </value>
            <value>
                <fullName>Interviews Completed</fullName>
            </value>
            <value>
                <fullName>Preparing Offer</fullName>
            </value>
            <value>
                <fullName>Offer Extended</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Accepted</fullName>
            </value>
            <value>
                <fullName>Closed - Declined</fullName>
            </value>
            <value>
                <fullName>Closed - Position Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DEX450_Exercises/force-app/main/default/classes/CandidateKeyRESTService.cls
//TODO #1 - Annotate the class as a RestRource. The urlMapping should be /Candidate/JobApp.

global class CandidateKeyRESTService {

    //TODO #2 - Annotate the method to process POST requests.

    global static Boolean submitEmployeeReferral(String posId, Candidate__c c){
        // this webservice receives a position Id, JobApplication and Candidate and creates the
        // JobApplication and optionally the Candidate, depending on whether or not it already exists
        
        System.debug('submitEmployeeReferral BEGIN');
        
        // first we check to see if we'll need to create a candidate or not
        boolean cCreate = true; // default to true
        System.debug('Querying for existing candidate record...');
        if (c.Email__c != null){
            String uKey = c.Last_Name__c.toLowerCase() + c.Email__c.toLowerCase();
            // query to find dupes
            if ([select count() from Candidate__c where unique_key__c = :uKey] >= 1) {
                cCreate=false;
                // set c to be the dupe candidate so we can get the Id value of the candidate later
                c = [select Id from Candidate__c where unique_key__c = :uKey limit 1];
                System.debug('Existing record found: ' + c.Id);
            }
        }
        
        // create a boolean to catch any errors in case we need to rollback
        boolean err = false;
        
        // create the candidate if necessary based off previous check
        if (cCreate){
            System.debug('No record found, creating Candidate...');
            try{
                insert c;
                System.debug('Candidate record created successfully with id: ' + c.Id);
            } catch (System.DmlException e) {
                //update our err flag
                err = true;
                System.debug('error bulk inserting new candidate record');
                for (Integer k = 0; k < e.getNumDml(); k++) {
                    // Process exception here
                    System.debug(e.getDmlMessage(k));
                }
            } catch (Exception ex) {
                System.debug('An error occurred while inserting the candidate record: ' + ex.getMessage());
            }
        }
        
        // if there has been no error then create the Job Application
        if (!err){
            System.debug('Creating the Application...');
            Job_Application__c j = new Job_Application__c();
            j.Status__c = 'Open';
            j.Stage__c = 'New';
            j.Position__c = posId;
            j.Candidate__c = c.Id;
            
            try{
                insert j;
                System.debug('Application record created successfully with id: ' + j.Id);
            } catch (System.DmlException e) {
                System.debug('error bulk inserting new job application');
                for (Integer k = 0; k < e.getNumDml(); k++) {
                    // Process exception here
                    System.debug(e.getDmlMessage(k));
                }
            } catch (Exception ex) {
                System.debug('An error occurred while inserting the application record: ' + ex.getMessage());
            }
        }
        
        System.debug('submitEmployeeReferral END');
        
        // check for errors and return the success flag
        if (!err) {
            return true;
        } else {
        //  further error handling here
            return false;
        }   
    }
}