oop-four-pillars/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of service vendor accounts.</description>
    <inlineHelpText>Active - Service vendor currently services our products.
Inactive - Service vendor no longer services our products.
Archived - Service vendor goes out of business.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Used to track certifications.</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Certification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of certification.</description>
    <inlineHelpText>Active - Certification is currently being given.
Retired - Certification is no longer being given.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>Used to track courses.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Certification associated with a course.</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of course.</description>
    <inlineHelpText>Active - Course is currently being taught.
Retired - Course is no longer being taught.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Attendee__c/Course_Attendee__c.object-meta.xml
<CustomObject>
    <description>Used to track a student who attends a course.</description>
    <label>Course Attendee</label>
    <nameField>
        <displayFormat>ATTENDEE-{00000}</displayFormat>
        <label>Course Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course_Attendee__c/fields/Course_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Course_Delivery__c</fullName>
    <description>Course delivery that student is attending.</description>
    <label>Course Delivery</label>
    <referenceTo>Course_Delivery__c</referenceTo>
    <relationshipLabel>Course Attendees</relationshipLabel>
    <relationshipName>Course_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Attendee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of course attendee.</description>
    <inlineHelpText>Enrolled - Student is enrolled in course delivery.
Completed - Student attended course delivery.
Course Cancelled - AW Computing cancelled course delivery.
No Show - Student did not show up for course delivery.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Course Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/Course_Delivery__c.object-meta.xml
<CustomObject>
    <description>Used to track each time a course is delivered.</description>
    <label>Course Delivery</label>
    <nameField>
        <displayFormat>DELIVERY-{00000}</displayFormat>
        <label>Course Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <description>Course being delivered.</description>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Deliveries</relationshipLabel>
    <relationshipName>Course_Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the course delivery.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DEX450_Exercises/force-app/main/default/classes/CourseTrigger_Test.cls
@isTest
public class CourseTrigger_Test {

    // Variables used in test
    static final String RETIRED = 'Retired';
    static final String TECHNICIAN = 'Technician';
    static final String ENROLLED = 'Enrolled';
    static final String SCHEDULED = 'Scheduled';
    static final String CANCELLED = 'Cancelled';
    static final String DELIVERED = 'Delivered';

    @testSetup
    static void setupData(){

        List<Account> testAccounts = LoadDataTestFactory.loadAccounts();
        List<Contact> testContacts = LoadDataTestFactory.loadContacts();
        List<Certification__c> testCerts = LoadDataTestFactory.loadCertifications();
        List<Course__c> testCourses = LoadDataTestFactory.loadCourses();
        List<User> testUsers = LoadDataTestFactory.createUsers();
        List<Course_Delivery__c> testCourseDeliveries = LoadDataTestFactory.loadCourseDeliveries();
        List<Course_Attendee__c> testCourseAttendes = LoadDataTestFactory.loadCourseAttendees();

    }

    @isTest
    static void checkStatusTestPreventRetirement(){
        // Look at Courses which are active
        List<Course__c> activeToRetired = [SELECT Status__c FROM Course__c WHERE Status__c != :RETIRED];
        // In these active courses, look for enrolled students where Course_Delivery__c is Scheduled
        List<Course_Delivery__c> scheduledDeliveries = [SELECT Status__c, (SELECT Status__c FROM Course_Attendees__r WHERE Status__c = :ENROLLED)
                                                          FROM Course_Delivery__c
                                                         WHERE Status__c = :SCHEDULED
                                                           AND Course__c IN :activeToRetired];

        // We want to make sure we have actual data to work with (not firing blanks)
        System.assertNotEquals(0, activeToRetired.size());
        System.assertNotEquals(0, scheduledDeliveries.size());

        // Change everything to retired
        for(Course__c retire : activeToRetired){
            retire.Status__c = RETIRED;
        }
        Database.SaveResult[] lsr = Database.update(activeToRetired, false);
        for(Database.SaveResult sr : lsr){
            if(!sr.isSuccess()){
                System.assertEquals('Course has enrolled students', sr.getErrors()[0].getMessage());
            }
        }
    }
/*
    //@isTest
    static void checkStatusTestCancelDelivery(){
        // If no students are enrolled, course is OK to retire, unless it has already been delivered.
        // Also, Course_Delivery__c should be cancelled by trigger where there are no enrolled students.
        List<Course__c> activeToRetired = [SELECT Status__c FROM Course__c WHERE Status__c != :RETIRED];
        List<Course_Delivery__c> nonCancelledDeliveries = [SELECT Status__c, (SELECT Status__c FROM Course_Attendees__r WHERE Status__c = :ENROLLED)
                                                             FROM Course_Delivery__c
                                                            WHERE Status__c IN (:DELIVERED, :SCHEDULED)
                                                              AND Course__c IN :activeToRetired];
        List<Course_Attendee__c> unEnroll = new List<Course_Attendee__c>();
        List<Course_Delivery__c> deliveredDeliveries = new List<Course_Delivery__c>();
        List<Course_Delivery__c> scheduledDeliveries = new List<Course_Delivery__c>();

        // We want to make sure we have actual data to work with
        System.assertNotEquals(0, activeToRetired.size());
        System.assertNotEquals(0, nonCancelledDeliveries.size());

        // Collect Course_Delivery__c according to status. If delivered, we'll check later that it stayed delivered
        // Else if scheduled, should be cancelled
        for(Course_Delivery__c cd : nonCancelledDeliveries){
            if(cd.Status__c == DELIVERED){
                deliveredDeliveries.add(cd);
            } else {
                scheduledDeliveries.add(cd);
            }
            // Un-enroll all students otherwise we won't be allowed to retire the course
            for(Course_Attendee__c ca : cd.Course_Attendees__r){
                if(ca.Status__c == ENROLLED){
                    ca.Status__c = '';
                    unEnroll.add(ca);
                }
            }
        }
        update unEnroll;

        // Change status of course to retired
        for(Course__c retire : activeToRetired){
            retire.Status__c = RETIRED;
        }
        update activeToRetired;

        // Scheduled deliveries should be cancelled
        List<Course_Delivery__c> cancelledDeliveries = [SELECT Id, Status__c FROM Course_Delivery__c WHERE id IN :scheduledDeliveries];
        for(Course_Delivery__c cancelledDelivery : cancelledDeliveries){
            System.assertEquals(CANCELLED, cancelledDelivery.Status__c);
        }

        // Delivered deliveries should remain delivered
        List<Course_Delivery__c> notCancelledDeliveries = [SELECT Id, Status__c FROM Course_Delivery__c WHERE id IN :deliveredDeliveries];
        for(Course_Delivery__c deliveredDelivery : notCancelledDeliveries){
            System.assertEquals(DELIVERED, deliveredDelivery.Status__c);
        }
    }
  */
}