oop-four-pillars/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of service vendor accounts.</description>
    <inlineHelpText>Active - Service vendor currently services our products.
Inactive - Service vendor no longer services our products.
Archived - Service vendor goes out of business.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Used to track certifications.</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Certification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of certification.</description>
    <inlineHelpText>Active - Certification is currently being given.
Retired - Certification is no longer being given.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>Used to track courses.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Certification associated with a course.</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of course.</description>
    <inlineHelpText>Active - Course is currently being taught.
Retired - Course is no longer being taught.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/Course_Delivery__c.object-meta.xml
<CustomObject>
    <description>Used to track each time a course is delivered.</description>
    <label>Course Delivery</label>
    <nameField>
        <displayFormat>DELIVERY-{00000}</displayFormat>
        <label>Course Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <description>Course being delivered.</description>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Deliveries</relationshipLabel>
    <relationshipName>Course_Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date the course will begin.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the course delivery.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DEX450_Exercises/force-app/main/default/classes/CourseDeliveryTrigger_Test.cls
@isTest
private class CourseDeliveryTrigger_Test {

    static final String ACTIVE = 'Active';
    static final String SCHEDULED = 'Scheduled';
    
    // Setup test data
    @testSetup static void setupData(){
     
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        System.runAs (thisUser){
            List<Account> testAccounts = LoadDataTestFactory.loadAccounts();
            List<Contact> testContacts = LoadDataTestFactory.loadContacts();
            List<Certification__c> testCerts = LoadDataTestFactory.loadCertifications();
            List<Course__c> testCourses = LoadDataTestFactory.loadCourses();
            Holiday newYearsEve = LoadDataTestFactory.createHoliday();
            List<Course_Delivery__c> testCourseDeliveries = LoadDataTestFactory.loadCourseDeliveries();
        }
    }
    
    @isTest
    static void insertCourseDeliverySuccess() {
        
        // Get the first Active Course
        List<Course__c> activeCourses = [SELECT Id, Name 
                                         FROM Course__c 
                                         WHERE Status__c = :ACTIVE LIMIT 1];
        Course__c course = activeCourses[0];
                
        Test.startTest();
        
        // Create a new Course Delivery record with a Start Date of 9/1/YYYY
        Course_Delivery__c courseDelivery = new Course_Delivery__c();
        courseDelivery.Course__c = course.Id;
        courseDelivery.Start_Date__c = Date.newInstance(Date.today().year(), 9, 1);
        
        // Add it to a list of Course Delivery records that will be passed
        // to the Database.insert method
        List<Course_Delivery__c> deliveries = new List<Course_Delivery__c>();
        deliveries.add(courseDelivery);
        Database.SaveResult[] saveResults = Database.insert(deliveries, false);
        
        Test.stopTest();
        
        // Verify that NO errors are passed back
        Integer errorCount = 0;
        for(Database.SaveResult sr : saveResults) {
            if(!sr.isSuccess()) { 
                if (sr.getErrors()[0].getMessage() == 
                    'Course Delivery cannot be scheduled because it starts on a holiday.')
                    ++errorCount;
            }
        }
        System.assertEquals(0, errorCount);
    }
    
    @isTest
    static void insertCourseDeliveryFailure() {
        
        // Get the first Active Course
        List<Course__c> activeCourses = [SELECT Id, Name 
                                         FROM Course__c 
                                         WHERE Status__c = :ACTIVE LIMIT 1];
        Course__c course = activeCourses[0];

        Test.startTest();
        
        // Create a new Course Delivery record with a Start Date of 12/31/YYYY
        Course_Delivery__c courseDelivery = new Course_Delivery__c();
        courseDelivery.Course__c = course.Id;
        courseDelivery.Start_Date__c = Date.newInstance(Date.today().year(), 12, 31);
        
        // Add it to a list of Course Delivery records that will be passed
        // to the Database.insert method
        List<Course_Delivery__c> deliveries = new List<Course_Delivery__c>();
        deliveries.add(courseDelivery);
        Database.SaveResult[] saveResults = Database.insert(deliveries, false);
                
        Test.stopTest();
        
        // Verify that an error was passed back
        Integer errorCount = 0;
        for(Database.SaveResult sr : saveResults) {
            if(!sr.isSuccess()) { 
                if (sr.getErrors()[0].getMessage() == 
                    'Course Delivery cannot be scheduled because it starts on a holiday.')
                    ++errorCount;
            }
        }
        System.assertEquals(1, errorCount);
        
    }
    
    @isTest
    static void updateCourseDeliverySuccess() {
        
        // Get the first Scheduled Course Delivery record.
        // All the Course Delivery Records were inserted in the TestSetup method
        List<Course_Delivery__c> courseDeliveries = [SELECT Id, Name 
                                                     FROM Course_Delivery__c 
                                                     WHERE Status__c = :SCHEDULED LIMIT 1];
        Course_Delivery__c courseDelivery = courseDeliveries[0];
        
        Test.startTest();
        
        // Update the record with a Start Date of 9/1/YYYY
        courseDelivery.Start_Date__c = Date.newInstance(Date.today().year(), 9, 1);
        
        // Add it to a list of Course Delivery records that will be passed
        // to the Database.update method
        List<Course_Delivery__c> deliveries = new List<Course_Delivery__c>();
        deliveries.add(courseDelivery);
        Database.SaveResult[] saveResults = Database.update(deliveries, false);
        
        Test.stopTest();
        
        // Verify that NO errors are passed back
        Integer errorCount = 0;
        for(Database.SaveResult sr : saveResults) {
            if(!sr.isSuccess()) { 
                if (sr.getErrors()[0].getMessage() == 
                    'Course Delivery cannot be scheduled because it starts on a holiday.')
                    ++errorCount;
            }
        }
        System.assertEquals(0, errorCount);
        
    }
    
    @isTest
    static void updateCourseDeliveryFailure() {
    
        // Get the first Scheduled Course Delivery record
        // All the Course Delivery Records were inserted in the TestSetup method
        List<Course_Delivery__c> courseDeliveries = [SELECT Id, Name 
                                                     FROM Course_Delivery__c 
                                                     WHERE Status__c = :SCHEDULED LIMIT 1];
        Course_Delivery__c courseDelivery = courseDeliveries[0];
        
        Test.startTest();
        
        // Update the record with a Start Date of 12/31/YYYY
        courseDelivery.Start_Date__c = Date.newInstance(Date.today().year(), 12, 31);
        
        // Add it to a list of Course Delivery records that will be passed
        // to the Database.update method
        List<Course_Delivery__c> deliveries = new List<Course_Delivery__c>();
        deliveries.add(courseDelivery);
        Database.SaveResult[] saveResults = Database.update(deliveries, false);
        
        Test.stopTest();
        
        // Verify that an error was passed back
        Integer errorCount = 0;
        for(Database.SaveResult sr : saveResults) {
            if(!sr.isSuccess()) { 
                if (sr.getErrors()[0].getMessage() == 
                    'Course Delivery cannot be scheduled because it starts on a holiday.')
                    ++errorCount;
            }
        }
        System.assertEquals(1, errorCount);
    }
}