oop-four-pillars/force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Used to track certifications.</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>Used to track courses.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Certification associated with a course.</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

DEX450_Exercises/force-app/main/default/classes/SearchCourses_CC_Test.cls
@isTest
private class SearchCourses_CC_Test {
    
    @testSetup
    private static void loadTestData() {
        
        // Load the test data. Use the LoadDataTestFactory class to load User, Certification and Course records (in that order)
        List<User> users = LoadDataTestFactory.createUsers();
        List<Certification__c> certs = LoadDataTestFactory.loadCertifications();
        List<Course__c> courses = LoadDataTestFactory.loadCourses();        
    }
    
    @isTest
    private static void testSearchCoursesNavigation() {
              
        // Set the current page
        PageReference searchCoursesPage = Page.SearchCoursesPage;
        Test.setCurrentPage(searchCoursesPage);
        
        // Do the test
        Test.startTest();
        
            // Instantiate the controller
            SearchCourses_CC sc = new SearchCourses_CC();
            
            // Get the list of CourseWrapper elements
            List<SearchCourses_CC.CourseWrapper> courseWrappers = sc.courseList;
            
            // Modify the list by checking all the elements
            for (SearchCourses_CC.CourseWrapper wrapper : courseWrappers) {
                wrapper.checked = true;
            }
            
            // Set modified list back to controller
            sc.courseList = courseWrappers;
            
            // Navigate to ListResultsPage by callng the listDeliveries method - capture the resulting url
            String url = sc.listDeliveries().getURL();
        
        Test.stopTest();
        
        // Verify the results
        
        // Check that all the elements have the boolean "checked" set to true
        List<SearchCourses_CC.CourseWrapper> courseWrappersModified = sc.courseList;
        Integer count = 0;
        for (SearchCourses_CC.CourseWrapper wrapper : courseWrappersModified) {
            if ( !wrapper.checked) count++;
        }
        System.assertEquals(0, count, 'ERROR: Found at least one CourseWrapper element not checked');
        
        // Check the correct navigation to ListCourseDeliveriesPage
        System.assertEquals(Page.ListCourseDeliveriesPage.getURL(), url, 'ERROR: Expected to navigate to /apex/listcoursedeliveriespage');
    }
}