oop-four-pillars/force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Used to track certifications.</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Certification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of certification.</description>
    <inlineHelpText>Active - Certification is currently being given.
Retired - Certification is no longer being given.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>Used to track courses.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Certification associated with a course.</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Length of a course.</description>
    <inlineHelpText>Number of days it takes to teach the course.</inlineHelpText>
    <label>Duration</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of course.</description>
    <inlineHelpText>Active - Course is currently being taught.
Retired - Course is no longer being taught.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/Course_Delivery__c.object-meta.xml
<CustomObject>
    <description>Used to track each time a course is delivered.</description>
    <label>Course Delivery</label>
    <nameField>
        <displayFormat>DELIVERY-{00000}</displayFormat>
        <label>Course Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <description>Course being delivered.</description>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Deliveries</relationshipLabel>
    <relationshipName>Course_Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Instructor that will teach a course.</description>
    <label>Instructor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Is_Instructor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Course_Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>City where a course will take place.</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Tokyo, JP</fullName>
            </value>
            <value>
                <fullName>Singapore, SG</fullName>
            </value>
            <value>
                <fullName>Paris, FR</fullName>
            </value>
            <value>
                <fullName>London, GB</fullName>
            </value>
            <value>
                <fullName>Berlin, DE</fullName>
            </value>
            <value>
                <fullName>San Francisco, US</fullName>
            </value>
            <value>
                <fullName>Chicago, US</fullName>
            </value>
            <value>
                <fullName>Toronto, CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date the course will begin.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the course delivery.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DEX450_Exercises/force-app/main/default/classes/SearchCourses_CC.cls
public with sharing class SearchCourses_CC {

     /**
     *  This controller is used by both the SearchCoursesPage and ListCourseDeliveriesPage
     *  VF pages. Users will select courses using the checkboxes and then click
     *  to see the upcoming course deliveries for those courses.
     */

    // Represents the main course list
    public List<CourseWrapper> courseList {
        get {
            if (courseList == null) {
                courseList = new List<CourseWrapper>();
                for (Course__c course : [SELECT Name, Certification__r.Name, Duration__c, Status__c,
                                           (SELECT id FROM Course_Deliveries__r WHERE Status__c != 'Cancelled' 
                                            and Start_Date__c >= TODAY)
                                         FROM Course__c]) {
                    courseList.add(new CourseWrapper(course));
                }
            }
            return courseList;
        }
        set;
    }

    // Contains only the course selected
    public Map<Id, CourseWrapper> selectedCourses {
        get {
            if (selectedCourses == null) {
                selectedCourses = new Map<Id, CourseWrapper>();
            }
            return selectedCourses;
        }
        private set;
    }

    // Action that is triggered from the "See Upcoming Course Deliveries" button
    public PageReference listDeliveries() {

        // First clear out any previously selected courses
        selectedCourses.clear();

        // Add the newly selected courses to the map
        for (CourseWrapper cw : courseList) {
            if (cw.checked) {
                selectedCourses.put(cw.course.Id, cw);
            }
        }

        // Check to see if any courses actually selected
        if (selectedCourses.size() > 0) {
            return Page.ListCourseDeliveriesPage;
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select at least one Course'));
            return null;
        }       
    }

    // The list of deliveries for ListCourseDeliveriesPage
    public List<Course_Delivery__c> deliveries {
        get {
            if (deliveries == null) {
                deliveries = new List<Course_Delivery__c>([
                                     SELECT Name, Course__r.Name, Instructor__r.Name, Location__c, Start_Date__c, Status__c
                                       FROM Course_Delivery__c
                                      WHERE Course__c IN :selectedCourses.keySet()
                                        AND Status__c != 'Cancelled' and Start_Date__c >= TODAY
                                   ORDER BY Start_Date__c]);
            }
            return deliveries;
        }
        private set;
    }

    // Navigate back to original page (flushing the view state)
    public PageReference newSearch() {
        PageReference newPage = Page.SearchCoursesPage;
        newPage.setRedirect(true);
        return newPage;
    }

    // Wrapper class
    public class CourseWrapper {
        public Course__c course {get; set;}
        public Boolean checked {get; set;}
        public Integer count {get; set;}

        public CourseWrapper(Course__c c) {
            course = c;
            checked = false;
            count = c.Course_Deliveries__r.size();
        }
    }
}