oop-four-pillars/force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Used to track certifications.</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Certification__c/fields/Number_of_Certified_Professionals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Certified_Professionals__c</fullName>
    <description>Number of certified professionals for this certification.</description>
    <label># of Certified Professionals</label>
    <summaryForeignKey>Certification_Held__c.Certification__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Certification_Held__c/Certification_Held__c.object-meta.xml
<CustomObject>
    <description>Used to track each time a contact achieves a certification.</description>
    <label>Certification Held</label>
    <nameField>
        <displayFormat>CERTIFICATION-{00000}</displayFormat>
        <label>Certification Held Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications Held</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Certification_Held__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <description>Certification being achieved.</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Certifications Held</relationshipLabel>
    <relationshipName>Certifications_Held</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DEX450_Exercises/force-app/main/default/objects/Certification_Held__c/fields/Certified_Professional__c.field-meta.xml
<CustomField>
    <fullName>Certified_Professional__c</fullName>
    <description>Contact who is certified.</description>
    <label>Certified Professional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Technician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications Held</relationshipLabel>
    <relationshipName>Certifications_Held</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DEX450_Exercises/force-app/main/default/classes/SOQLInjection_CC.cls
public class SOQLInjection_CC {

    // The User's input
    public String name { get; set; }

    // Example input good: CERTIFICATION-00001
    // Example input bad:  test' OR name like '%

    public List<Certification_Held__c> queryResult { get; set; }

    public void query() {

        // trim whitespace from search term
        name = name.trim();

        // Example of safe dynamic soql with bind variable.
        // Bind variables using :expression mitigate SOQL Injection from string concatenation.
        //queryResult = [
        //   SELECT Name, Certified_Professional__r.Name, Certification__r.Name, Certification__r.Number_of_Certified_Professionals__c
        //     FROM Certification_Held__c
        //    WHERE Name = :name
        //    LIMIT 1
        //];
        
        // Example of unsafe dynamic soql with string concatenation.
        // Because the filter criteria is passed as-is from the web form,
        // this exposes a SOQL Injection vulnerability.
        //name = String.escapeSingleQuotes(name);
        String qryString =
             ' SELECT Name, Certified_Professional__r.Name, Certification__r.Name, Certification__r.Number_of_Certified_Professionals__c ' +
             ' FROM Certification_Held__c ' +
             ' WHERE Name =\'' + name + '\'';

        queryResult = Database.query( qryString );        
    }
}