custom-settings-demo/force-app/main/default/objects/State_Codes__c/State_Codes__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Tracks state names and abbreviations.</description>
    <label>State Codes</label>
</CustomObject>

custom-settings-demo/force-app/main/default/objects/State_Codes__c/fields/State_Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>State_Abbreviation__c</fullName>
    <description>The abbreviation for the state.</description>
    <label>State Abbreviation</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

custom-settings-demo/force-app/main/default/classes/CustomSettingsDemo.cls
public with sharing class CustomSettingsDemo {
    public CustomSettingsDemo() {

    }


    public static String getStateAbbreviation() {


        //State_Codes__c codes = State_Codes__c.getInstance('00eHu000001chmf');         // ID for Sales User Profile
        State_Codes__c codes = State_Codes__c.getInstance(UserInfo.getProfileId());     // UserInfo contains information about the current running user
        return codes.State_Abbreviation__c;
    }


}