oop-four-pillars/force-app/main/default/objects/Certification_Held__c/Certification_Held__c.object-meta.xml
<CustomObject>
    <description>Used to track each time a contact achieves a certification.</description>
    <label>Certification Held</label>
    <nameField>
        <displayFormat>CERTIFICATION-{00000}</displayFormat>
        <label>Certification Held Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications Held</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DEX450_Exercises/force-app/main/default/objects/Certification_Held__c/fields/Certified_Professional__c.field-meta.xml
<CustomField>
    <fullName>Certified_Professional__c</fullName>
    <description>Contact who is certified.</description>
    <label>Certified Professional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Technician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications Held</relationshipLabel>
    <relationshipName>Certifications_Held</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DEX450_Exercises/force-app/main/default/objects/Certification_Held__c/fields/Date_Achieved__c.field-meta.xml
<CustomField>
    <fullName>Date_Achieved__c</fullName>
    <description>Date certification was achieved.</description>
    <label>Date Achieved</label>
    <type>Date</type>
</CustomField>

DEX450_Exercises/force-app/main/default/classes/AccountDisplayCertsHeld_CX.cls
public with sharing class AccountDisplayCertsHeld_CX {
    /**
     *  This Extension Controller is used to populate
     *  a table of Certifications Held that are
     *  related to a specific Account and displayed
     *  in-line on the detail page for that Account
     */

    private final Account acct;

    public AccountDisplayCertsHeld_CX(ApexPages.StandardController stdController) {
        this.acct = (Account) stdController.getRecord();
    }
    
    public List<Certification_Held__c> results {
        get {
            if (results == null) {
                results = new List<Certification_Held__c> ([SELECT Id, Name, Date_Achieved__c, Certified_Professional__r.Name
                                                            FROM Certification_Held__c
                                                            WHERE Certified_Professional__r.AccountId = :acct.Id]);
            }
            return results;
        }
        private set;
    }
}