oop-four-pillars/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Use to create standard customer accounts.</description>
    <label>Customer</label>
</RecordType>

oop-four-pillars/force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Used to track certifications.</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>Used to track courses.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Certification associated with a course.</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Attendee__c/Course_Attendee__c.object-meta.xml
<CustomObject>
    <description>Used to track a student who attends a course.</description>
    <label>Course Attendee</label>
    <nameField>
        <displayFormat>ATTENDEE-{00000}</displayFormat>
        <label>Course Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course_Attendee__c/fields/Course_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Course_Delivery__c</fullName>
    <description>Course delivery that student is attending.</description>
    <label>Course Delivery</label>
    <referenceTo>Course_Delivery__c</referenceTo>
    <relationshipLabel>Course Attendees</relationshipLabel>
    <relationshipName>Course_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/Course_Delivery__c.object-meta.xml
<CustomObject>
    <description>Used to track each time a course is delivered.</description>
    <label>Course Delivery</label>
    <nameField>
        <displayFormat>DELIVERY-{00000}</displayFormat>
        <label>Course Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <description>Course being delivered.</description>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Deliveries</relationshipLabel>
    <relationshipName>Course_Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

oop-four-pillars/force-app/main/default/objects/Course_Delivery__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Instructor that will teach a course.</description>
    <label>Instructor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Is_Instructor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Course_Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

DEX450_Exercises/force-app/main/default/classes/LoadDataTestFactory.cls
@isTest
public class LoadDataTestFactory {
    
    public static List<Account> loadAccounts() {
        // We need to assign the Account to the correct recordtype after it has been loaded
        List<Account> initialAccounts = Test.loadData(Account.sObjectType, 'TestAccounts');
        for (Account a: initialAccounts) {
            if (a.Name.startsWith('SV')) {
                //Service Vendor recordType
                a.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Service Vendor').getRecordTypeId();             
            } else {
                //Customer recordType
                a.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            }       
        }
        update initialAccounts;
        return initialAccounts;
    }
    
    public static List<Contact> loadContacts() {
        // We need to assign the Contact to the correct recordtype after it has been loaded
        List<Contact> initialContacts = Test.loadData(Contact.sObjectType, 'TestContacts');
        for (Contact c: initialContacts) {
            if (c.LastName.startsWith('T')) {
                //Service Vendor recordType
                c.recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Technician').getRecordTypeId();             
            } else {
                //Standard recordType
                c.recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
            }       
        }
        update initialContacts;
        return initialContacts;
    }
    
    public static List<Certification__c> loadCertifications() {
        return Test.loadData(Certification__c.sObjectType, 'TestCertifications');
    }
    
    public static List<Course__c> loadCourses() {
        return Test.loadData(Course__c.sObjectType, 'TestCourses');
    }
    
    public static List<Course_Delivery__c> loadCourseDeliveries() {
        // Need to assign the Course Deliveries to an Instructor user after they have been loaded
        List<Course_Delivery__c> initialDeliveries = Test.loadData(Course_Delivery__c.sObjectType, 'TestCourseDeliveries');
        User instructor = [ select Id from User where Is_Instructor__c = true LIMIT 1 ];
        for (Course_Delivery__c cd: initialDeliveries) {
            cd.Instructor__c = instructor.Id;
        }
        update initialDeliveries;
        return initialDeliveries;
    }
    
    public static List<Course_Attendee__c> loadCourseAttendees() {
        return Test.loadData(Course_Attendee__c.sObjectType, 'TestCourseAttendees');
    }
    
    public static List<User> createUsers() {
        // We had problems loading the User data from Static Resource files and ended up having to create
        // them manually

        Id instructorProfileId = [SELECT Id FROM Profile WHERE Name = 'Instructor User' LIMIT 1].Id;
        Id trainingProfileId = [SELECT Id FROM Profile WHERE Name = 'Training User' LIMIT 1].Id;

        List<User> users = new List<User>();
        User trainingCoordinator = new User(Username='nsanchez@example.com',
                                            FirstName='Nicki', LastName=' Sanchez',
                                            email='nsanchez@example.com',
                                            alias='nsanchez',
                                            CommunityNickname='nsanchez',
                                            TimeZoneSidKey='America/Los_Angeles',
                                            LocaleSidKey='en_US', 
                                            EmailEncodingKey='UTF-8',
                                            ProfileId=trainingProfileId, 
                                            LanguageLocaleKey='en_US'
                                           );
        users.add(trainingCoordinator);
        User instructor = new User(Username='mholmes@example.com',
                                            FirstName='Minnie', LastName='Holmes',
                                            email='mholmes@example.com',
                                            alias='mholmes',
                                            CommunityNickname='mholmes',
                                            TimeZoneSidKey='America/Los_Angeles',
                                            LocaleSidKey='en_US', 
                                            EmailEncodingKey='UTF-8',
                                            ProfileId=instructorProfileId, 
                                            Is_Instructor__c=true,
                                            LanguageLocaleKey='en_US'
                                           );
        users.add(instructor);
        return users;
    }
    
    public static Holiday createHoliday(){
        Holiday newYearsEve = new Holiday(ActivityDate = 
                              Date.newInstance(Date.today().year(), 12, 31), 
                              Name = 'New Years Eve');
        insert newYearsEve;
        
        return newYearsEve;
    }
}